INSERT INTO POSTS (title, content, created_at, views) VALUES ('첫 번째 게시글', '안녕하세요. 반가워요!', CURRENT_TIMESTAMP, 10);
INSERT INTO POSTS (title, content, created_at, views) VALUES ('두 번째 게시글', '오늘의 날씨는 매우 맑음입니다.', CURRENT_TIMESTAMP, 5);
INSERT INTO POSTS (title, content, created_at, views) VALUES ('세 번째 게시글', 'Vibe Coding에 오신 것을 환영합니다.', CURRENT_TIMESTAMP, 20);
INSERT INTO POSTS (title, content, created_at, views) VALUES ('네 번째 게시글', 'DTO 패턴을 적용해보았습니다.', CURRENT_TIMESTAMP, 15);
INSERT INTO POSTS (title, content, created_at, views) VALUES ('다섯 번째 게시글', 'MyBatis를 사용하여 DB를 연동합니다.', CURRENT_TIMESTAMP, 8);
INSERT INTO POSTS (title, content, created_at, views) VALUES ('여섯 번째 게시글', 'H2는 가벼운 인메모리 데이터베이스입니다.', CURRENT_TIMESTAMP, 12);
INSERT INTO POSTS (title, content, created_at, views) VALUES ('일곱 번째 게시글', 'Thymeleaf를 이용한 뷰 렌더링.', CURRENT_TIMESTAMP, 7);
INSERT INTO POSTS (title, content, created_at, views) VALUES ('여덟 번째 게시글', 'Spring Boot 4.0.1 버전을 사용 중입니다.', CURRENT_TIMESTAMP, 30);
INSERT INTO POSTS (title, content, created_at, views) VALUES ('아홉 번째 게시글', '테일윈드 CSS로 디자인을 입혔습니다.', CURRENT_TIMESTAMP, 18);
INSERT INTO POSTS (title, content, created_at, views) VALUES ('열 번째 게시글', '페이징 기능이 정상 작동하는지 확인하세요.', CURRENT_TIMESTAMP, 25);
