CREATE TABLE IF NOT EXISTS POSTS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    views INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS POST_TAGS (
    ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    POST_NO  BIGINT NOT NULL,
    TAG_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT fk_post_tags_posts FOREIGN KEY (POST_NO) REFERENCES POSTS(ID)
);
